<?php
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_principal')->toHtml();
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('apelos')->toHtml();
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('produtos')->toHtml();
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banners')->toHtml();
?>